name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # This triggers the workflow on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Using your EC2 as a self-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    - name: Run Integration Tests
      run: npm run test:integration

    - name: Build Docker Image
      run: sudo docker build -t my-html-app .

    - name: Stop and Remove Old Container
      run: |
        sudo docker stop my-html-container || true
        sudo docker rm my-html-container || true

    - name: Run New Container
      run: sudo docker run -d -p 8080:80 --name my-html-container my-html-app

    - name: Wait for Container to Initialize
      run: sleep 15

    - name: Check Running Containers
      run: |
        sudo docker ps -a
        sudo docker logs my-html-container || true
