name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Uses the EC2 runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker (Optional, if pulling from a private registry)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: sudo docker build -t my-html-app .

      - name: Stop and Remove Old Container
        run: |
          sudo docker stop my-html-container || true
          sudo docker rm my-html-container || true

      - name: Run New Container
        run: sudo docker run -d -p 80:80 --name my-html-container my-html-app
