name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Using EC2 as a self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker (if not installed)
        run: |
          if ! command -v docker &> /dev/null; then
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

      - name: Build Docker Image
        run: sudo docker build -t my-html-app .

      - name: Stop and Remove Old Container (if exists)
        run: sudo docker rm -f my-html-container || true

      - name: Run New Container
        run: sudo docker run -d -p 80:80 --restart unless-stopped --name my-html-container my-html-app
